### ISSUE TITLE
TA comments

### ISSUE THREAD

**Issue by Rashedul** [STAT545-UBC-students/hw07-lsloboda#3]
- This command `devtools::install_github("STAT545-UBC-students/hw07-lsloboda/powers-master")` gives this message:

```
Error: HTTP error 404.
  Not Found

  Rate limit remaining: 59/60
  Rate limit reset at: 2018-11-29 09:12:02 UTC
``

- I cant open the powers directory. Do you have comment?

**Comment by lsloboda** [comment]
Hi @Rashedul 

Thanks for letting me know. I had an issue where the powers folder was not viewable on GitHub and I couldn't figure out why. I suspect it had to do with the way I nested the folders. I have gotten rid of the nesting and brought all the files into the root folder and now it seems to be working!

Please try this command instead (I've updated the README too):
devtools::install_github("lsloboda/powers")

Thanks again and please let me know if you have any other issues!
Laura

**Comment by Rashedul** [comment]
@lsloboda Thanks for commenting back.

Yes, now I can install your package and I updated your grade as well. Few additional comments.

- The readme and the vignette described the package very well with example.

- Adding boxcox and apply functionalities were great ideas. 

- It was a solid submission with basic requirements. 

- Great coding style and strategies.

**Comment by lsloboda** [comment]
@Rashedul Great, thanks! =)
